(function () {
  window.NEO_PORTFOLIO_PROJECTS = [
    {
      id: 'frontline',
      title: 'FRONTLINE',
      category: 'Competitive FPS',
      status: 'In Development',
      tagline: 'A cinematic competitive FPS built around speed, tactics, and arcane technology.',
      description: 'Neo Soft debut title: a multiplayer FPS experience combining tactical combat, hero identity, and high-impact visual direction.',
      thumbnail: 'img/portfolio/frontline.jpg',
      href: 'project.html?id=frontline',
      externalHref: 'https://store.steampowered.com/app/1772220/Frontline_New_Revolution/',
      externalLabel: 'Wishlist on Steam',
      details: ['Competitive FPS', 'Hero identity', 'Arcane technology', 'Built in Unreal Engine']
    },
    {
      id: 'fatum',
      title: 'FATUM',
      category: 'Arena Combat',
      status: 'Prototype',
      tagline: 'A futuristic multiplayer FPS set after collapse, where only machines remain.',
      description: 'A service project focused on spectator systems, grenade gameplay, replication fixes, and readable combat in fast arena modes.',
      thumbnail: 'img/portfolio/fatum.jpg',
      href: 'project.html?id=fatum',
      externalHref: 'games.html',
      externalLabel: 'View games',
      details: ['Arena combat', 'Spectator systems', 'Grenade gameplay', 'Replication fixes']
    },
    {
      id: 'imobi',
      title: 'Imobi',
      category: 'Mobile Product',
      status: 'Prototype',
      tagline: 'A mobile property discovery app built around map-first browsing.',
      description: 'Imobi simplifies property discovery with an interactive map, listing filters, and a cleaner flow for finding the next home.',
      thumbnail: 'img/imobi-icon.png',
      href: 'project.html?id=imobi',
      externalHref: 'games.html',
      externalLabel: 'View product',
      details: ['Android', 'iOS', 'Interactive map', 'Property discovery']
    },
    {
      id: 'neolytics',
      title: 'Neolytics',
      category: 'Steam Analytics',
      status: 'Prototype',
      tagline: 'A viability analysis platform for Steam projects before production scales.',
      description: 'Neolytics helps teams read market signals, clarify positioning, and make better decisions before committing more production time.',
      thumbnail: 'img/portfolio/neolytics.png',
      href: 'project.html?id=neolytics',
      externalHref: 'https://project-pqd61.vercel.app/',
      externalLabel: 'Open project',
      details: ['Steam signals', 'Market positioning', 'Decision support', 'Production planning']
    },
    {
      id: 'vector-toys',
      title: 'Vector Toys Calculator',
      category: 'Pricing Tool',
      status: 'Delivered Work',
      tagline: 'A pricing hub for 3D printing costs, materials, printer profiles, and margins.',
      description: 'Vector Toys Calculator centralizes the pricing workflow for 3D printed products, keeping cost inputs and margin-based decisions in one place.',
      thumbnail: 'img/portfolio/vector-toys.png',
      href: 'project.html?id=vector-toys',
      externalHref: 'https://victorhmrod.github.io/vectortoys-calculator/',
      externalLabel: 'Open project',
      details: ['3D print costs', 'Material profiles', 'Margin pricing', 'Delivered tool']
    },
    {
      id: 'world-procedural-generator',
      title: 'World Procedural Generator',
      category: 'Unreal Engine Plugin',
      status: 'Fab Marketplace',
      tagline: 'Procedural terrain, biomes, and placement tools for ambitious Unreal worlds.',
      description: 'A production plugin built to help teams author vast open worlds with faster iteration and reliable procedural workflows.',
      thumbnail: 'img/portfolio/world-procedural-generator.jpg',
      href: 'project.html?id=world-procedural-generator',
      externalHref: 'https://www.fab.com/pt-br/listings/5b18f63c-894d-40b8-846a-bf4670ee9eeb',
      externalLabel: 'Open on Fab',
      details: ['Procedural worlds', 'Biome tools', 'Placement workflows', 'Unreal Engine']
    },
    {
      id: 'neo-library',
      title: 'Neo Library',
      category: 'Unreal Engine Toolkit',
      status: 'Fab Marketplace',
      tagline: 'A utility layer for localization, settings, and Blueprint-ready production helpers.',
      description: 'A focused Unreal Engine library that packages recurring studio needs into practical tools for game teams and technical designers.',
      thumbnail: 'img/portfolio/neo-library.jpg',
      href: 'project.html?id=neo-library',
      externalHref: 'https://www.fab.com/pt-br/listings/b4b9e699-62b2-4829-868b-cc2cc3a6bf88',
      externalLabel: 'Open on Fab',
      details: ['Localization', 'Settings', 'Blueprint helpers', 'Production utilities']
    },
    {
      id: 'replicated-explosion',
      title: 'Replicated Explosion Plugin',
      category: 'Networked Gameplay',
      status: 'Fab Marketplace',
      tagline: 'Network-ready explosive gameplay with replicated effects and tuned physics.',
      description: 'A gameplay plugin designed for multiplayer Unreal projects that need reliable impact, VFX synchronization, and configurable blast behavior.',
      thumbnail: 'img/portfolio/replicated-explosion.jpg',
      href: 'project.html?id=replicated-explosion',
      externalHref: 'https://www.fab.com/pt-br/listings/13134d3a-256f-44bc-9052-3dd69e87932d',
      externalLabel: 'Open on Fab',
      details: ['Network gameplay', 'Replicated VFX', 'Blast physics', 'Multiplayer ready']
    },
    {
      id: 'advanced-loot-generator',
      title: 'Advanced Loot Generator',
      category: 'Gameplay Systems',
      status: 'Fab Marketplace',
      tagline: 'A procedural loot foundation for configurable, network-ready reward systems.',
      description: 'A plugin for Unreal teams that need flexible loot generation, replication support, and production-minded controls for item drops.',
      thumbnail: 'img/portfolio/advanced-loot-generator.jpg',
      href: 'project.html?id=advanced-loot-generator',
      externalHref: 'https://www.fab.com/listings/09a9dc9f-7a75-4280-8d7b-0f00c86daf37',
      externalLabel: 'Open on Fab',
      details: ['Procedural loot', 'Reward systems', 'Replication support', 'Configurable drops']
    }
  ];
})();
